Spot Reviews
Chernosmaga/parking pull request #16
Opened 2024-06-07 13:28 UTC by marmeladov98

Now you can interact with parking space reviews - create, update, delete reviews, as well as receive a list of your reviews and a list of user reviews of a spots.

2024-06-07 14:03 UTC, Chernosmaga requested changes
Оставил несколько комментариев. Не знал знал ты или нет, но можно чистить неиспользуемые импорты одним махом (я заметил пару у тебя)

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/java/com/example/parking/booking/controller/BookingController.java
> +@Validated
Спасибо, вылетело из головы снова))

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/java/com/example/parking/booking/service/BookingServiceImpl.java
> +        if (SpotState.FREE != spot.getSpotState()) {
Лучше всё же через equals, что сравнивались не ссылки, а значения

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/java/com/example/parking/spot/dto/SpotReviewsShortDto.java
> +public class SpotReviewsShortDto {
Всё же, мне кажется, что лучше было бы, если бы в сущности Review был User, это не так режет глаз и выглядит как-то правильнее))

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/java/com/example/parking/spot/model/SpotReviews.java
> +    private Long spotId;
Привязал бы всё же сущность Spot и доставал идентификатор, а то мало ли, вдруг он изменится (всякое в жизни бывает) и информация будет некорректной

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/resources/db/changelog/changeset/create-spots-table.yaml
> +                  type: smallint
У меня в прошлый раз БД ругалась на этот тип данных

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/resources/db/changelog/changeset/create-spots-table.yaml
> +                  type: varchar(1000)
А если ссылка на картинку будет оооооочень далеко на серваке, а у тебя всего 1к символов?))

2024-06-07 14:03 UTC, Chernosmaga commented on src/main/resources/db/changelog/changeset/create-spots-table.yaml
> +              INSERT INTO spots (latitude, longitude, "spot_state", is_storeyed, floor, "picture", "is_handicapped", average_rating)
Надеюсь, ты перед удалением заметил мои пасхалки)))))

2024-06-24 17:44 UTC, marmeladov98 commented on src/main/java/com/example/parking/spot/dto/SpotReviewsShortDto.java
> +public class SpotReviewsShortDto {
Нет смысла в каждом элементе массива дублировать инфу о юзере. Этот метод выводит  отзывы по всем спотам, которые оставлял 1 пользователь - 
![изображение_2024-06-24_204248537](https://github.com/Chernosmaga/parking/assets/108763442/c6b6f60c-24a8-4c2e-aa4f-4b05bfcc5e58)

А вот то, что ты хочешь для метода, который выводит отзывы конкретного метода - 
![image](https://github.com/Chernosmaga/parking/assets/108763442/67b4ee35-ab8a-4281-ac09-ba083f69ffb2)

2024-06-24 17:51 UTC, marmeladov98 commented on src/main/java/com/example/parking/booking/service/BookingServiceImpl.java
> +        if (SpotState.FREE != spot.getSpotState()) {
Поправил

2024-06-24 17:51 UTC, marmeladov98 commented on src/main/java/com/example/parking/spot/model/SpotReviews.java
> +    private Long spotId;
Готово

2024-06-24 17:51 UTC, marmeladov98 commented on src/main/resources/db/changelog/changeset/create-spots-table.yaml
> +                  type: smallint
Поменял на integer

2024-06-24 17:51 UTC, marmeladov98 commented on src/main/resources/db/changelog/changeset/create-spots-table.yaml
> +                  type: varchar(1000)
Поменял на varchar

2024-06-24 17:53 UTC, Chernosmaga approved these changes
Претензий не имею))

2024-06-24 19:04 UTC, Buriyone approved these changes

2024-06-25 14:35 UTC, merged