feat: add Spot
Chernosmaga/parking pull request #7
Opened 2024-04-23 20:15 UTC by Qualiter

2024-04-23 20:19 UTC, alesya87 approved these changes
Молодец

2024-04-24 04:57 UTC, Chernosmaga requested changes
Метод обновления я бы немного укоротил, много кода. В целом есть пара вопросов, которые не дают покоя

2024-04-24 04:57 UTC, Chernosmaga commented on src/main/java/com/example/parking/spot/dto/NewSpotRequestDto.java
> +    private BigDecimal longitude;
Интересно, а зачем BigDecimal, а не Long, к примеру?

2024-04-24 04:57 UTC, Chernosmaga commented on src/main/java/com/example/parking/spot/service/SpotServiceImpl.java
>  @RequiredArgsConstructor
Добавь, пожалуйста, логирование

2024-04-24 13:33 UTC, Qualiter commented on src/main/java/com/example/parking/spot/dto/NewSpotRequestDto.java
> +    private BigDecimal longitude;
Для поддержки дробных значений широты и долготы. Long режет дробную часть.

2024-04-24 13:44 UTC, Qualiter commented
> Метод обновления я бы немного укоротил, много кода. В целом есть пара вопросов, которые не дают покоя. Спасибо, что вынес в отдельную ветку

"В целом есть пара вопросов, которые не дают покоя" - это те вопросы, которые ты задал ниже? Логи и Long?

"я бы немного укоротил, много кода" - напиши, пожалуйста, подробнее, какие возможности для уменьшения кода ты видишь?

2024-04-24 14:58 UTC, Chernosmaga commented
> > Метод обновления я бы немного укоротил, много кода. В целом есть пара вопросов, которые не дают покоя. Спасибо, что вынес в отдельную ветку
> 
> "В целом есть пара вопросов, которые не дают покоя" - это те вопросы, которые ты задал ниже? Логи и Long?
> 
> "я бы немного укоротил, много кода" - напиши, пожалуйста, подробнее, какие возможности для уменьшения кода ты видишь?

Обсудили в чате, в ТГ. Вопросов теперь нет 😃

2024-04-24 14:58 UTC, Chernosmaga approved these changes

2024-04-24 16:38 UTC, marmeladov98 reviewed
Выглядит здорово. Но есть пару вопросов...

2024-04-24 16:38 UTC, marmeladov98 commented on src/main/java/com/example/parking/exception/controller/ErrorController.java
> -            MethodArgumentTypeMismatchException.class})
А можете рассказать что это за эксепшн?

2024-04-24 16:38 UTC, marmeladov98 commented on src/main/java/com/example/parking/spot/dto/NewSpotRequestDto.java
> +    private BigDecimal longitude;
А почему строкой нельзя? Мы же не планируем потом какие-то арифметические операции с этими переменным производить. А из-за BigDecimal и других дробных числовых переменных могут проблемы повылезать при конвертации в формат БД и из БД в приложении.

2024-04-24 19:02 UTC, Qualiter commented on src/main/java/com/example/parking/spot/dto/NewSpotRequestDto.java
> +    private BigDecimal longitude;
Насколько я знаю, поиск будет быстрее по числам, чем по строкам. Плюс я сторонник числа хранить в числовых форматах.
Не исключено, что нам когда-то понадобится вычислять какие-то смещения по широте и долготе при навигации пользователя по парковке.
Миша, про какие проблемы при конвертации дробных чисел ты говоришь? Сталкивался или есть статья какая-то? Скинь, пожалуйста, если есть.

2024-04-24 20:17 UTC, marmeladov98 approved these changes
Отличная работа! Давай зачетку

2024-04-24 20:58 UTC, merged