Linking entites
Chernosmaga/parking pull request #8
Opened 2024-05-05 12:05 UTC by marmeladov98

Связаны сущности: 
User <-> Vehicle
Booking <- User, Vehicle, Spot

+ Рефакторинг кода, изменены и долбавлены новые таблицы
+ Обновлены Postman тесты

2024-05-06 06:39 UTC, Chernosmaga requested changes
Проведена большая работа за короткие сроки. Горжусь! Добавь ещё, пожалуйста, недостающую документацию. Хотя бы немного, остальную часть обновим на Code Review

2024-05-06 06:39 UTC, Chernosmaga commented on src/main/java/com/example/parking/booking/dto/BookingFullDto.java
> +public record BookingFullDto(Long id, UserShortDto booker, SpotId spot, Vehicle vehicle, LocalDateTime start, LocalDateTime end,
Есть ли необходимость создавать отдельную сущность, если нужно передать только id? Может стоит изменить тип на Long?

2024-05-06 06:39 UTC, Chernosmaga commented on src/main/java/com/example/parking/user/model/User.java
> +    private Set<Vehicle> vehicles;
Почему решили всё же отказаться от id'шников?

2024-05-06 06:39 UTC, Chernosmaga commented on src/main/java/com/example/parking/vehicle/controller/VehicleController.java
> +        return vehicleService.create(vehicle, authentication.getName());
Зачем передавать здесь класс `Authentication` и за что он отвечает?

2024-05-06 08:30 UTC, alesya87 commented on src/main/java/com/example/parking/user/model/User.java
> +    private Set<Vehicle> vehicles;
вроде совместно решили, что используем LAZY, поэтому оставляем сущность

2024-05-06 08:31 UTC, alesya87 commented on src/main/java/com/example/parking/vehicle/controller/VehicleController.java
> +        return vehicleService.create(vehicle, authentication.getName());
из него берется номер телефона текущего юзера, чтобы потом к этому юзеру привязать викл

2024-05-06 08:42 UTC, alesya87 commented on src/main/java/com/example/parking/booking/dto/BookingFullDto.java
> +public record BookingFullDto(Long id, UserShortDto booker, SpotId spot, Vehicle vehicle, LocalDateTime start, LocalDateTime end,
тут наверное dto spotId, наверное id из сущности сам по себе не подтянется

2024-05-06 08:44 UTC, alesya87 commented on src/main/java/com/example/parking/booking/dto/BookingFullDto.java
> +public record BookingFullDto(Long id, UserShortDto booker, SpotId spot, Vehicle vehicle, LocalDateTime start, LocalDateTime end,
но его тогда в папку с dto надо

2024-05-06 08:46 UTC, Chernosmaga commented on src/main/java/com/example/parking/vehicle/controller/VehicleController.java
> +        return vehicleService.create(vehicle, authentication.getName());
А не проще передавать id пользователя для привязки? Или данный вариант предоставляет авторизованный формат?

2024-05-06 08:48 UTC, Chernosmaga commented on src/main/java/com/example/parking/booking/dto/BookingFullDto.java
> +public record BookingFullDto(Long id, UserShortDto booker, SpotId spot, Vehicle vehicle, LocalDateTime start, LocalDateTime end,
В методе можно взять из сущности id и закинуть в dto. Обсудили с Мишей этот вопрос, надо бы передавать хоть и краткую, но информацию во фронт, потому что id передавать на фронт - нецелесообразно. Они там ведь не будут делать запрос в БД, это мы должны им вернуть осмысленные данные

2024-05-11 10:05 UTC, Chernosmaga approved these changes

2024-05-11 23:22 UTC, alesya87 approved these changes

2024-05-12 09:11 UTC, Qualiter approved these changes
Катя молодец!

2024-05-12 09:12 UTC, Qualiter approved these changes
Супер!

2024-05-12 09:13 UTC, Qualiter approved these changes

2024-05-12 09:14 UTC, Qualiter approved these changes

2024-05-12 09:28 UTC, merged